### ISSUE TITLE
1F1 function unstable 

### ISSUE THREAD

**Issue by glennmoy** [JuliaApproximation/HypergeometricFunctions.jl#13]
I was recently using this package to compute the 1F1 function in order to calculate the expected [absolute error of a normal distribution](https://en.wikipedia.org/wiki/Normal_distribution#Moments).

The function became unstable for small sigma, i.e. large, negative z which I believe is a consequence of the taylor series expansion around this area.

See the image for a comparison with a [closed form solution](https://en.wikipedia.org/wiki/Folded_normal_distribution) I found using the error function:

![image](https://user-images.githubusercontent.com/16086784/64542740-051f6780-d31c-11e9-92f2-68b24a8f073c.png)

Just wanted to bring this to your attention. Thanks

**Comment by dlfivefifty** [comment]
Thanks. At the moment this package doesn't really have an active "developer", the original code was implemented by @MikaelSlevinsky if you are lucky will look at this, but has probably moved on to ther things. It was cleaned up by @jwscook but similarly I'm not sure if he is interested. I'm also not able to fix.

That said, I'm an active "Maintainer" so if you make a PR to fix it, I'll happily merge.

**Comment by MikaelSlevinsky** [comment]
Your explanation is correct. For generalized hypergeometric functions, only the Taylor series and a continued fraction thanks to @jwscook are implemented. There may be instabilities in both at the moment.

If you want more accuracy, you should be able to use `BigFloat` and convert the result to `Float64`. But this is just an artifact of multiple dispatch, not a moral extension of MPFR. That is, there is no guaranteed rounding and even no guarantee of "if I use m+n bits, my result will be accurate to n bits of precision."

**Comment by glennmoy** [comment]
Thanks for both your responses.

@dlfivefifty that's all reasonable - in the off chance this package was still in use I just thought I'd highlight it. I don't think I'm in a position to open PRs as I was just interested in this function.

@MikaelSlevinsky I think the closed form is more than sufficient for my needs but thanks for taking the time to explain!

**Comment by dlfivefifty** [comment]
The package is definitely still in use: we use in SingularIntegralEquations.jl. Its just not our primary focus.

**Comment by jwscook** [comment]
Hi @glennmoy, can you boil this down to one value of sigma that represents a failure?

**Comment by glennmoy** [comment]
Yes, of course. I'll run you through my 

```julia
julia> using HypergeometricFunctions

julia> _1F1(μ, σ) = mFn([-0.5], [0.5], [-0.5 * (μ / σ)^2])
_1F1 (generic function with 1 method)

julia> m = 1.0;

julia> sig = collect(0:0.1:1);

julia> _1F1.(Ref(m), sig)
11-element Array{Array{Float64,1},1}:
 [NaN]     
 [-233.795]
 [6.26657] 
 [4.17799] 
 [3.13831] 
 [2.52791] 
 [2.13855] 
 [1.87673] 
 [1.69345] 
 [1.56083] 
 [1.46216] 
```

So below `sig <= 0.1` it becomes unstable, which is also visible in the graph.

Manifest:
```julia
    Status `~/Projects/HyperGeomBug/Manifest.toml`
  [9e28174c] BinDeps v0.8.10
  [b99e7846] BinaryProvider v0.5.6
  [49dc2e85] Calculus v0.5.0
  [34da2185] Compat v2.1.0
  [fa6b7ba4] DualNumbers v0.6.2
  [34004b35] HypergeometricFunctions v0.1.1
  [77ba4419] NaNMath v0.3.2
  [276daf66] SpecialFunctions v0.8.0
  [30578b45] URIParser v0.4.0
  [2a0f44e3] Base64 
  [ade2ca70] Dates 
  [8bb1440f] DelimitedFiles 
  [8ba89e20] Distributed 
  [b77e0a4c] InteractiveUtils 
  [76f85450] LibGit2 
  [8f399da3] Libdl 
  [37e2e46d] LinearAlgebra 
  [56ddb016] Logging 
  [d6f4376e] Markdown 
  [a63ad114] Mmap 
  [44cfe95a] Pkg 
  [de0858da] Printf 
  [3fa0cd96] REPL 
  [9a3f8284] Random 
  [ea8e919c] SHA 
  [9e88b42a] Serialization 
  [1a1011a3] SharedArrays 
  [6462fe0b] Sockets 
  [2f01184e] SparseArrays 
  [10745b16] Statistics 
  [8dfed614] Test 
  [cf7118a7] UUIDs 
  [4ec0a83e] Unicode
```

**Comment by jwscook** [comment]
I find that `BigFloat` helps here. Before `mFn` was misbehaving at arguments of `-50.0`, but with `BigFloat` and the continued fraction fallback method

```
 [(-i, HypergeometricFunctions.mFn([-0.5], [0.5], -BigFloat(i))) for i in (0:5:195)]
```

which seems to work ok, but watch at for large negative arguments because:

```
[(-i, HypergeometricFunctions.mFncontinuedfraction([-0.5], [0.5], -BigFloat(i))) for i in (0:5:195)]
```

gives different answers below `-175`.

**Comment by dlfivefifty** [comment]
I would seriously consider using ` BigFloat ` + IntervalArithmetic.jl to get guaranteed results, even for ` Float64 ` computation. The extra compute time is worth the “headache free” ness

**Comment by MikaelSlevinsky** [comment]
I've been working on some rational approximations to generalized hypergeometric functions in linear time. I should get around to updating this repository in the near future. But as a preview, here's some specialized code for 1F1:

```julia
function drummond(α::T, β::T, z::T) where T
    if norm(z) < eps(real(T))
        return one(T)
    end
    ζ = inv(z)
    Nlo = (β/α)*ζ
    Dlo = (β/α)*ζ
    Tlo = Nlo/Dlo
    if norm(α+1) < eps(real(T))
        return Tlo
    end
    Nmid = (((β+1)*(2)*ζ - (α+1))*Nlo + (β+1)*(2)*ζ)/(α+1)
    Dmid = ((β+1)*(2)*ζ - (α+1))*Dlo/(α+1)
    Tmid = Nmid/Dmid
    if norm(α+2) < eps(real(T))
        return Tmid
    end
    Dhi = (((β+2)*(3)*ζ - (α+3))*Dmid + ((β+4)*ζ-1)*Dlo )/(α+2)
    Nhi = (((β+2)*(3)*ζ - (α+3))*Nmid + ((β+4)*ζ-1)*Nlo + (β+4)*ζ)/(α+2)
    Thi = Nhi/Dhi
    if norm(α+3) < eps(real(T))
        return Thi
    end
    k = 2
    Dhi, Dmid, Dlo = ( ((β+k+1)*(k+2)*ζ-(α+2k+1))*Dhi + k*((β+2k+2)*ζ-1)*Dmid + k*(k-1)*ζ*Dlo )/(α+k+1), Dhi, Dmid
    Nhi, Nmid, Nlo = ( ((β+k+1)*(k+2)*ζ-(α+2k+1))*Nhi + k*((β+2k+2)*ζ-1)*Nmid + k*(k-1)*ζ*Nlo +2ζ)/(α+k+1), Nhi, Nmid
    Thi, Tmid, Tlo = Nhi/Dhi, Thi, Tmid
    k += 1
    while (abs(Thi-Tmid) > 10*abs(Thi)*eps(real(T)) || abs(Tmid-Tlo) > 10*abs(Tmid)*eps(real(T))) && k < 10_000
        Dhi, Dmid, Dlo = ( ((β+k+1)*(k+2)*ζ-(α+2k+1))*Dhi + k*((β+2k+2)*ζ-1)*Dmid + k*(k-1)*ζ*Dlo )/(α+k+1), Dhi, Dmid
        Nhi, Nmid, Nlo = ( ((β+k+1)*(k+2)*ζ-(α+2k+1))*Nhi + k*((β+2k+2)*ζ-1)*Nmid + k*(k-1)*ζ*Nlo )/(α+k+1), Nhi, Nmid
        Thi, Tmid, Tlo = Nhi/Dhi, Thi, Tmid
        k += 1
    end
    return isnan(Thi) ? isnan(Tmid) ? Tlo : Tmid : Thi
end
```

If I increase the precision of BigFloat so that the Taylor series is accurate to 16 digits (so that I can compare pointwise relative error), the rational approximation seems to work very far from the origin, even in 64-bit!

```julia
julia> setprecision(512)
512

julia> [(-i, (drummond(-0.5, 0.5, -1.0*i) - Float64(HypergeometricFunctions.mFn([-0.5], [0.5], -BigFloat(i))))/Float64(HypergeometricFunctions.mFn([-0.5], [0.5], -BigFloat(i)))) for i in (0:5:195)]
40-element Array{Tuple{Int64,Float64},1}:
 (0, 0.0)                       
 (-5, -1.1203450499926778e-15)  
 (-10, 3.1692399487856034e-16)  
 (-15, 2.587674499232558e-15)   
 (-20, -9.076017017157472e-15)  
 (-25, -6.0132121527204375e-15) 
 (-30, -7.867977410094392e-15)  
 (-35, 1.4907469384007348e-14)  
 (-40, -1.6004667434137855e-14) 
 (-45, -1.2997752765390771e-14) 
 (-50, -1.7007932359608418e-15) 
 (-55, -1.5675879651129268e-14) 
 (-60, -3.752128028979282e-14)  
 (-65, 1.2182170498724638e-14)  
 (-70, -3.5576457834698235e-14) 
 (-75, 6.480562022792809e-15)   
 (-80, 2.1289422632967643e-15)  
 (-85, -2.6741201737632997e-14) 
 (-90, -4.352424411131879e-14)  
 (-95, -2.981888989340247e-14)  
 (-100, 7.135678421228464e-14)  
 (-105, 1.9169760983083844e-14) 
 (-110, 6.211153897884065e-14)  
 (-115, -3.1774979057159347e-15)
 (-120, -1.1527501786882483e-14)
 (-125, -3.836578057646379e-14) 
 (-130, 4.1839891793348926e-14) 
 (-135, 1.2800363206908633e-13) 
 (-140, -2.4936130605975927e-13)
 (-145, -1.3882488465443675e-13)
 (-150, -4.271497431887807e-14) 
 (-155, 9.901352871206037e-14)  
 (-160, 7.051561394248856e-14)  
 (-165, 7.053127496614438e-14)  
 (-170, 4.365953954760333e-14)  
 (-175, -1.1151776626155039e-13)
 (-180, -5.5576598031326053e-14)
 (-185, -2.596601547920617e-13) 
 (-190, 1.2447502895809926e-13) 
 (-195, -2.440152042546816e-15) 

```

N.B. closed-forms are usually unbeatable when you have them!

**Comment by jonas-kr** [comment]
I think I noticed a related issue where the 1F1 function becomes unstable for large negative values. However, the relation 1F1(a, b, z) = exp(z) * 1F1(b-a, a, -z) provides a workaround. 
MWE:

```
julia> mFn([-5/6],[1.0],-200.0)
-5.718048908157637e64

julia> mFn([1+5/6],[1.0],200.0)*exp(-200.0)
88.22663013443177
```

I have to admit that I am not entirely sure about the accuracy of this modification but it suffices for my needs.

**Comment by MikaelSlevinsky** [comment]
(An endless supply of) transformations are in the scope of the package, see for example all the ones implemented for 2F1 https://github.com/JuliaMath/HypergeometricFunctions.jl/blob/master/src/gauss.jl. These can always be added for special cases but don't supplant general purpose code. The idea here is to use these rational approximations:
```julia
julia> HypergeometricFunctions.drummond1F1(-5/6, 1.0, -200.0)
88.22663013446518

julia> HypergeometricFunctions.wenigerpFq([-5/6], [1.0], -200.0)
88.22663013443305

julia> HypergeometricFunctions.drummond1F1(big"-5.0"/6, big"1.0", big"-200.0")
88.2266301344338764609440813700233224838195976713073726730018868341352792630444

julia> HypergeometricFunctions.wenigerpFq([big"-5.0"/6], [big"1.0"], big"-200.0")
88.22663013443387646094408137002332248381959767130737267300188683413527926311957

julia> 

```

**Comment by jonas-kr** [comment]
Thank you very much for your quick reply - I was quite tired yesterday and did not have a closer look at the provided approximations...
