### ISSUE TITLE
 Copy across `directed` and `Undirected` from SingularIntegralEquations.jl, preserving history

### ISSUE THREAD

**Issue by jwscook** [JuliaApproximation/HypergeometricFunctions.jl#2]
See #1 for keeping hold of git history belonging to the relevant files.

**Comment by jwscook** [comment]
@dlfivefifty Is `Directed` complicated enough to warrant it's own repository? Is it wise to have this code duplicated in this repo and in SingularIntegralEquations?

**Comment by dlfivefifty** [comment]
The ` Directed ` stuff should probably stay in SingularIntegralEquations for now as it’s a bit specialised usage.

**Comment by jwscook** [comment]
Righto. I'll leave it there.

**Comment by jwscook** [comment]
This means that the precompilation issue with SingularIntegralEquations will spread across to this package.

**Comment by jwscook** [comment]
... maybe. I'll keep looking into what I can tear out.

**Comment by jwscook** [comment]
My case is indeed <sub>3</sub>F<sub>3</sub>. Is your thinking to create this package without e.g. <sub>2</sub>F<sub>1</sub>, and add the specific ones later?

**Comment by dlfivefifty** [comment]
That’s not a good idea. Just remove the ` Directed ` code as a user can just evaluate at ` x+0im ` or ` x-0im ` to indicate side of branch.

**Comment by jwscook** [comment]
Ok, good.
