### ISSUE TITLE
This line is wrong

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/HypergeometricFunctions.jl#4]
https://github.com/JuliaApproximation/HypergeometricFunctions.jl/blob/03f2d1c1a959629e99fc13272ff75012c38f2f7f/src/HypergeometricFunctions.jl#L22

**Comment by dlfivefifty** [comment]
There should not be a `using .HypergeometricFunctions` and having an `export` outside of a module doesn't make sense

**Comment by jwscook** [comment]
Woops, last commit is for #3
