### ISSUE TITLE
Generalised Hypergeometric function by continued fraction

### ISSUE THREAD

**Issue by jwscook** [JuliaApproximation/HypergeometricFunctions.jl#8]
The convergence properties of generalised hypergeometric functions by continued fraction might be better. I'll try it out!

http://functions.wolfram.com/HypergeometricFunctions/HypergeometricPFQ/10/

**Comment by chakravala** [comment]
Yes, they might be better, but I believe I read somewhere that it is not better for all parameter ranges.

I'd be interested in helping out with this also, I am researching some related theoretical error bounds

**Comment by jwscook** [comment]
Cool! I'm just tapping away on the train and still need to finalise some things before I push my changes.

From what I can see so far is that K=-1 for some parameters, which makes it blow up.

**Comment by jwscook** [comment]
@chakravala I've just pushed to `dev`
